from dotenv import load_dotenv
import json

load_dotenv()

from config import app, db
from models.property import Property
from models.contact_information import ContactInformation
from models.review import Review

# Your JSON data (for simplicity, assuming it's stored in a variable `data`)
data = {
    "listings": [
        {
            "title": "Spacious Family Home",
            "type": "For Sale",
            "price": "Ksh 5,000,000",
            "bedrooms": 4,
            "bathrooms": 3,
            "location": "Westlands",
            "city": "Nairobi",
            "propertyFeatures": ["Swimming Pool", "Garden", "Parking"],
            "squareFootage": 3000,
            "contactInformation": {
                "name": "John Doe",
                "phone": "+123456789",
                "email": "john.doe@example.com",
            },
            "image": "https://images.prop24.com/xqtazogtorkszdydmb6airqxli/Crop237x198",
        },
        {
            "title": "Country Farmhouse",
            "type": "For Sale",
            "price": "Ksh 15,000,000",
            "bedrooms": 4,
            "bathrooms": 3,
            "location": "Kiambu",
            "city": "Nairobi",
            "propertyFeatures": ["Rural Charm", "Acreage", "Barn"],
            "squareFootage": 3500,
            "contactInformation": {
                "name": "Charles Brown",
                "phone": "+777888999",
                "email": "charles.brown@example.com",
            },
            "image": "https://images.prop24.com/2tf6infkcr2dm5livozkyasmrm/Crop237x198",
        },
        {
            "title": "City View Condo",
            "type": "For Sale",
            "price": "Ksh 28,000,000",
            "bedrooms": 3,
            "bathrooms": 3,
            "location": "Upper Hill",
            "city": "Nairobi",
            "propertyFeatures": ["City Views", "Luxury Amenities", "Security"],
            "squareFootage": 2300,
            "contactInformation": {
                "name": "Grace Johnson",
                "phone": "+555666777",
                "email": "grace.johnson@example.com",
            },
            "image": "https://images.prop24.com/rbzyiaeeziwswxm6tbzxk7zc5y/Crop237x198",
        },
        {
            "title": "Scenic Cottage",
            "type": "For Sale",
            "price": "Ksh 10,000,000",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Milimani",
            "city": "Nakuru",
            "propertyFeatures": ["Mountain Views", "Garden", "Fireplace"],
            "squareFootage": 1800,
            "contactInformation": {
                "name": "Linda Brown",
                "phone": "+111222333",
                "email": "linda.brown@example.com",
            },
            "image": "https://images.prop24.com/azlu6hcsdzy34jt23wsgfd5mem/Crop237x198",
        },
        {
            "title": "Lakeview Retreat",
            "type": "For Sale",
            "price": "Ksh 14,000,000",
            "bedrooms": 4,
            "bathrooms": 3,
            "location": "Mawanga",
            "city": "Nakuru",
            "propertyFeatures": ["Lake Views", "Deck", "Boat Dock"],
            "squareFootage": 2800,
            "contactInformation": {
                "name": "Peter Wilson",
                "phone": "+333444555",
                "email": "peter.wilson@example.com",
            },
            "image": "https://images.prop24.com/efsf64ac6hpyijbrqmnnm6eotm/Crop237x198",
        },
        {
            "title": "Lakeside Bungalow",
            "type": "For Sale",
            "price": "Ksh 12,000,000",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "Kisian",
            "city": "Kisumu",
            "propertyFeatures": ["Lakeside Living", "Garden", "Outdoor Lounge"],
            "squareFootage": 1500,
            "contactInformation": {
                "name": "Sarah White",
                "phone": "+777888999",
                "email": "sarah.white@example.com",
            },
            "image": "https://images.prop24.com/45x7sa7gxkourbch7wk5pc5nxm/Crop237x198",
        },
        {
            "title": "City Center Apartment",
            "type": "For Sale",
            "price": "Ksh 18,000,000",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Migosi",
            "city": "Kisumu",
            "propertyFeatures": ["City Center", "Balcony", "Security"],
            "squareFootage": 2000,
            "contactInformation": {
                "name": "Daniel White",
                "phone": "+999888777",
                "email": "daniel.white@example.com",
            },
            "image": "https://images.prop24.com/t5kbq7xcrfuo5fg2kh734orzpu/Crop237x198",
        },
        {
            "title": "Rural Retreat",
            "type": "For Sale",
            "price": "Ksh 16,000,000",
            "bedrooms": 4,
            "bathrooms": 3,
            "location": "Kabarak",
            "city": "Nakuru",
            "propertyFeatures": ["Peaceful Surroundings", "Garden", "Fire Pit"],
            "squareFootage": 2600,
            "contactInformation": {
                "name": "Olivia Brown",
                "phone": "+555666777",
                "email": "olivia.brown@example.com",
            },
            "image": "https://images.prop24.com/vu4l5mu3v4peuejtij5kiuaf6y/Crop237x198",
        },
        {
            "title": "Lavish Lakeside Home",
            "type": "For Sale",
            "price": "Ksh 30,000,000",
            "bedrooms": 5,
            "bathrooms": 4,
            "location": "Dunga",
            "city": "Kisumu",
            "propertyFeatures": ["Lakeside Living", "Infinity Pool", "Boat Dock"],
            "squareFootage": 4000,
            "contactInformation": {
                "name": "Sophia Wilson",
                "phone": "+888777666",
                "email": "sophia.wilson@example.com",
            },
            "image": "https://images.prop24.com/7bclckhttdo4x2cer52432c2iq/Crop237x198",
        },
        {
            "title": "Urban Oasis",
            "type": "For Sale",
            "price": "Ksh 25,000,000",
            "bedrooms": 3,
            "bathrooms": 3,
            "location": "Mamboleo",
            "city": "Kisumu",
            "propertyFeatures": ["City Views", "Rooftop Terrace", "Luxury Finishes"],
            "squareFootage": 2200,
            "contactInformation": {
                "name": "Henry Johnson",
                "phone": "+999888777",
                "email": "henry.johnson@example.com",
            },
            "image": "https://images.prop24.com/h3qkdbts4dezhbzk2tsw4pand4/Crop237x198",
        },
        {
            "title": "Tranquil Forest Cabin",
            "type": "For Sale",
            "price": "Ksh 14,000,000",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "Kapsabet",
            "city": "Nandi",
            "propertyFeatures": ["Forest Views", "Deck", "Fireplace"],
            "squareFootage": 1500,
            "contactInformation": {
                "name": "Isaac White",
                "phone": "+111222333",
                "email": "isaac.white@example.com",
            },
            "image": "https://images.prop24.com/o6ju2wbdhabp24yqhwfzpdmqau/Crop237x198",
        },
        {
            "title": "Safari Lodge",
            "type": "For Sale",
            "price": "Ksh 35,000,000",
            "bedrooms": 6,
            "bathrooms": 5,
            "location": "Maasai Mara",
            "city": "Narok",
            "propertyFeatures": ["Wildlife Views", "Safari Experience", "Pool"],
            "squareFootage": 6000,
            "contactInformation": {
                "name": "Anna Brown",
                "phone": "+333444555",
                "email": "anna.brown@example.com",
            },
            "image": "https://images.prop24.com/i5j3aumvm44cojqgpr27cdveta/Crop237x198",
        },
        {
            "title": "Mountain Chalet",
            "type": "For Sale",
            "price": "Ksh 20,000,000",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Nandi Hills",
            "city": "Nandi",
            "propertyFeatures": ["Mountain Views", "Fireplace", "Outdoor Patio"],
            "squareFootage": 1800,
            "contactInformation": {
                "name": "Eva Johnson",
                "phone": "+555666777",
                "email": "eva.johnson@example.com",
            },
            "image": "https://images.prop24.com/jwrkdt7ky4jofyp7dsntw7juqa/Crop237x198",
        },
        {
            "title": "Oceanfront Villa",
            "type": "For Sale",
            "price": "Ksh 32,000,000",
            "bedrooms": 4,
            "bathrooms": 3,
            "location": "Diani",
            "city": "Kwale",
            "propertyFeatures": ["Ocean Views", "Infinity Pool", "Private Beach"],
            "squareFootage": 3800,
            "contactInformation": {
                "name": "William Brown",
                "phone": "+888777666",
                "email": "william.brown@example.com",
            },
            "image": "https://images.prop24.com/w55q76pkksne2nne672z3cz2b4/Crop237x198",
        },
        {
            "title": "Artistic Loft",
            "type": "For Sale",
            "price": "Ksh 28,000,000",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Karen",
            "city": "Nairobi",
            "propertyFeatures": ["Open Concept", "Art Studio", "City Views"],
            "squareFootage": 2000,
            "contactInformation": {
                "name": "Sophie Wilson",
                "phone": "+999888777",
                "email": "sophie.wilson@example.com",
            },
            "image": "https://images.prop24.com/qpi75taahtj7rvxb3t7sxjeiwe/Crop237x198",
        },
        {
            "title": "Historic Manor",
            "type": "For Sale",
            "price": "Ksh 40,000,000",
            "bedrooms": 6,
            "bathrooms": 5,
            "location": "Thika",
            "city": "Nairobi",
            "propertyFeatures": ["Historic Charm", "Expansive Gardens", "Ballroom"],
            "squareFootage": 5500,
            "contactInformation": {
                "name": "Oliver Johnson",
                "phone": "+111222333",
                "email": "oliver.johnson@example.com",
            },
            "image": "https://images.prop24.com/xqtazogtorkszdydmb6airqxli/Crop237x198",
        },
        {
            "title": "Modern Townhouse",
            "type": "For Sale",
            "price": "Ksh 26,000,000",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Kitisuru",
            "city": "Nairobi",
            "propertyFeatures": ["Contemporary Design", "Private Garden", "Security"],
            "squareFootage": 2200,
            "contactInformation": {
                "name": "Emma Brown",
                "phone": "+333444555",
                "email": "emma.brown@example.com",
            },
            "image": "https://images.prop24.com/mqd7qrya732rxuyvfschswtnfm/Crop237x198",
        },
        {
            "title": "Downtown Apartment",
            "type": "For Rent",
            "price": "Ksh 22,000/month",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "CBD",
            "city": "Nairobi",
            "propertyFeatures": ["Central Location", "Security", "Modern Finishes"],
            "squareFootage": 1200,
            "contactInformation": {
                "name": "Sophia Brown",
                "phone": "+555666777",
                "email": "sophia.brown@example.com",
            },
            "image": "https://images.prop24.com/vr2qsudr5iqm4z5essipbf3mse/Crop237x198",
        },
        {
            "title": "Cosy Studio",
            "type": "For Rent",
            "price": "Ksh 15,000/month",
            "bedrooms": 1,
            "bathrooms": 1,
            "location": "Lang'ata",
            "city": "Nairobi",
            "propertyFeatures": ["Compact Design", "Close to Amenities", "Security"],
            "squareFootage": 800,
            "contactInformation": {
                "name": "Daniel Wilson",
                "phone": "+888777666",
                "email": "daniel.wilson@example.com",
            },
            "image": "https://images.prop24.com/t33s5mjve42vyylbx7ddoofgjq/Crop237x198",
        },
        {
            "title": "Luxury Condo",
            "type": "For Rent",
            "price": "Ksh 30,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Kilimani",
            "city": "Nairobi",
            "propertyFeatures": ["High-End Finishes", "Balcony", "Swimming Pool"],
            "squareFootage": 1800,
            "contactInformation": {
                "name": "Grace Brown",
                "phone": "+999888777",
                "email": "grace.brown@example.com",
            },
            "image": "https://images.prop24.com/arf5kbfcwss4cwtdg3w6yanifq/Crop237x198",
        },
        {
            "title": "Sunny Penthouse",
            "type": "For Rent",
            "price": "Ksh 35,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Westlands",
            "city": "Nairobi",
            "propertyFeatures": ["Rooftop Terrace", "City Views", "Modern Design"],
            "squareFootage": 2200,
            "contactInformation": {
                "name": "Lucas Johnson",
                "phone": "+111222333",
                "email": "lucas.johnson@example.com",
            },
            "image": "https://images.prop24.com/ugozk5b33rki5dt7wi23bkw6y4/Crop237x198",
        },
        {
            "title": "Eco-Friendly Apartment",
            "type": "For Rent",
            "price": "Ksh 25,000/month",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Karen",
            "city": "Nairobi",
            "propertyFeatures": [
                "Green Building",
                "Energy-Efficient",
                "Fitness Center",
            ],
            "squareFootage": 1400,
            "contactInformation": {
                "name": "Ava Brown",
                "phone": "+777888999",
                "email": "ava.brown@example.com",
            },
            "image": "https://images.prop24.com/2rxim646jmng57tgiklubbtg6m/Crop237x198",
        },
        {
            "title": "Chic Townhouse",
            "type": "For Rent",
            "price": "Ksh 28,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Runda",
            "city": "Nairobi",
            "propertyFeatures": ["Private Garden", "Modern Finishes", "Security"],
            "squareFootage": 2000,
            "contactInformation": {
                "name": "Lily Wilson",
                "phone": "+333444555",
                "email": "lily.wilson@example.com",
            },
            "image": "https://images.prop24.com/kq6es7ccbvsr3dokpe2f5iosz4/Crop237x198",
        },
        {
            "title": "Serenity Studio",
            "type": "For Rent",
            "price": "Ksh 18,000/month",
            "bedrooms": 1,
            "bathrooms": 1,
            "location": "Kasarani",
            "city": "Nairobi",
            "propertyFeatures": [
                "Tranquil Setting",
                "Modern Design",
                "Close to Nature",
            ],
            "squareFootage": 700,
            "contactInformation": {
                "name": "Oliver Johnson",
                "phone": "+999888777",
                "email": "oliver.johnson@example.com",
            },
            "image": "https://images.prop24.com/srfufbi4wdoxxotqrav53e4cfu/Crop237x198",
        },
        {
            "title": "Rustic Cabin",
            "type": "For Rent",
            "price": "Ksh 12,000/month",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "Limuru",
            "city": "Kiambu",
            "propertyFeatures": ["Countryside Charm", "Fireplace", "Scenic Views"],
            "squareFootage": 1000,
            "contactInformation": {
                "name": "Emma Brown",
                "phone": "+111222333",
                "email": "emma.brown@example.com",
            },
            "image": "https://images.prop24.com/gorx6zlny5z2vkw447qqkl464a/Crop237x198",
        },
        {
            "title": "Seaside Retreat",
            "type": "For Rent",
            "price": "Ksh 40,000/month",
            "bedrooms": 4,
            "bathrooms": 3,
            "location": "Nyali",
            "city": "Mombasa",
            "propertyFeatures": ["Beach Access", "Private Pool", "Ocean Views"],
            "squareFootage": 2800,
            "contactInformation": {
                "name": "David Wilson",
                "phone": "+777888999",
                "email": "david.wilson@example.com",
            },
            "image": "https://images.prop24.com/avmzhkfimvwf7qegbzntvuta3u/Crop237x198",
        },
        {
            "title": "Modern Duplex",
            "type": "For Rent",
            "price": "Ksh 32,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Muthaiga",
            "city": "Nairobi",
            "propertyFeatures": ["Duplex Layout", "Balcony", "Security"],
            "squareFootage": 2200,
            "contactInformation": {
                "name": "Sophie Brown",
                "phone": "+555666777",
                "email": "sophie.brown@example.com",
            },
            "image": "https://images.prop24.com/arf5kbfcwss4cwtdg3w6yanifq/Crop237x198",
        },
        {
            "title": "Central Loft",
            "type": "For Rent",
            "price": "Ksh 20,000/month",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "CBD",
            "city": "Nairobi",
            "propertyFeatures": ["Urban Living", "High Ceilings", "Modern Finishes"],
            "squareFootage": 1300,
            "contactInformation": {
                "name": "Ethan Brown",
                "phone": "+777888999",
                "email": "ethan.brown@example.com",
            },
            "image": "https://images.prop24.com/2fdt2bgw6a6eqzzzo5vnjmkzy4/Crop237x198",
        },
        {
            "title": "Tranquil Retreat",
            "type": "For Rent",
            "price": "Ksh 28,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Karen",
            "city": "Nairobi",
            "propertyFeatures": ["Serene Environment", "Garden", "Security"],
            "squareFootage": 1900,
            "contactInformation": {
                "name": "Lily Brown",
                "phone": "+333444555",
                "email": "lily.brown@example.com",
            },
            "image": "https://images.prop24.com/wr34cejinj677s4yymtostingq/Crop237x198",
        },
        {
            "title": "Modern Studio",
            "type": "For Rent",
            "price": "Ksh 15,000/month",
            "bedrooms": 1,
            "bathrooms": 1,
            "location": "Westlands",
            "city": "Nairobi",
            "propertyFeatures": ["Sleek Design", "Close to Amenities", "Security"],
            "squareFootage": 700,
            "contactInformation": {
                "name": "Olivia Wilson",
                "phone": "+999888777",
                "email": "olivia.wilson@example.com",
            },
            "image": "https://images.prop24.com/2ejjax2n3qbkpxx554juikgqq4/Crop237x198",
        },
        {
            "title": "Elegant Apartment",
            "type": "For Rent",
            "price": "Ksh 25,000/month",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Kilimani",
            "city": "Nairobi",
            "propertyFeatures": ["Sophisticated Style", "Balcony", "Swimming Pool"],
            "squareFootage": 1500,
            "contactInformation": {
                "name": "Lucas Brown",
                "phone": "+111222333",
                "email": "lucas.brown@example.com",
            },
            "image": "https://images.prop24.com/l3f7vz2ryibmu23wi4d64vcfoq/Crop237x198",
        },
        {
            "title": "Nature's Haven",
            "type": "For Rent",
            "price": "Ksh 18,000/month",
            "bedrooms": 1,
            "bathrooms": 1,
            "location": "Limuru",
            "city": "Kiambu",
            "propertyFeatures": ["Wooded Setting", "Peaceful Ambiance", "Security"],
            "squareFootage": 800,
            "contactInformation": {
                "name": "Emma Wilson",
                "phone": "+111222333",
                "email": "emma.wilson@example.com",
            },
            "image": "https://images.prop24.com/afc7urzzungr2d5edj4zygfe7i/Crop237x198",
        },
        {
            "title": "Charming Cottage",
            "type": "For Rent",
            "price": "Ksh 22,000/month",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "Nakuru",
            "city": "Nakuru",
            "propertyFeatures": ["Cozy Atmosphere", "Country Living", "Garden"],
            "squareFootage": 1000,
            "contactInformation": {
                "name": "Sophie Johnson",
                "phone": "+555666777",
                "email": "sophie.johnson@example.com",
            },
            "image": "https://images.prop24.com/wvinz36azyva335p252gyhz7qa/Crop237x198",
        },
        {
            "title": "Sunny Condo",
            "type": "For Rent",
            "price": "Ksh 30,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Runda",
            "city": "Nairobi",
            "propertyFeatures": ["Bright Interiors", "Balcony", "Security"],
            "squareFootage": 1800,
            "contactInformation": {
                "name": "Daniel Brown",
                "phone": "+888777666",
                "email": "daniel.brown@example.com",
            },
            "image": "https://images.prop24.com/sjgp2xeskez7hehwjkxcttjtnm/Crop237x198",
        },
        {
            "title": "Lakeview Apartment",
            "type": "For Rent",
            "price": "Ksh 26,000/month",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Naivasha",
            "city": "Nakuru",
            "propertyFeatures": ["Lake Views", "Modern Finishes", "Security"],
            "squareFootage": 1600,
            "contactInformation": {
                "name": "Ava Brown",
                "phone": "+555666777",
                "email": "ava.brown@example.com",
            },
            "image": "https://images.prop24.com/a3zw6gpvck4566p5ivbva2vxpa/Crop237x198",
        },
        {
            "title": "Urban Oasis",
            "type": "For Rent",
            "price": "Ksh 22,000/month",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "Nakuru",
            "city": "Nakuru",
            "propertyFeatures": ["City Living", "Gym", "Security"],
            "squareFootage": 1200,
            "contactInformation": {
                "name": "Sophia Wilson",
                "phone": "+333444555",
                "email": "sophia.wilson@example.com",
            },
            "image": "https://images.prop24.com/dogbtzkopldh5777am7mdvl4nm/Crop237x198",
        },
        {
            "title": "Rustic Cabin",
            "type": "For Rent",
            "price": "Ksh 18,000/month",
            "bedrooms": 1,
            "bathrooms": 1,
            "location": "Limuru",
            "city": "Kiambu",
            "propertyFeatures": ["Wooden Charm", "Nature Retreat", "Security"],
            "squareFootage": 900,
            "contactInformation": {
                "name": "David White",
                "phone": "+999888777",
                "email": "david.white@example.com",
            },
            "image": "https://images.prop24.com/c6z5i5d32ttaeycsnhqrynx3fa/Crop237x198",
        },
        {
            "title": "Oceanfront Apartment",
            "type": "For Rent",
            "price": "Ksh 35,000/month",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Nyali",
            "city": "Mombasa",
            "propertyFeatures": ["Sea Views", "Beach Access", "Swimming Pool"],
            "squareFootage": 1600,
            "contactInformation": {
                "name": "Sophie Johnson",
                "phone": "+555666777",
                "email": "sophie.johnson@example.com",
            },
            "image": "https://images.prop24.com/gbnlomumirq35k6enegf62tvxm/Crop237x198",
        },
        {
            "title": "Palm Oasis Villa",
            "type": "For Rent",
            "price": "Ksh 45,000/month",
            "bedrooms": 3,
            "bathrooms": 3,
            "location": "Bamburi",
            "city": "Mombasa",
            "propertyFeatures": ["Tropical Gardens", "Private Pool", "Security"],
            "squareFootage": 2200,
            "contactInformation": {
                "name": "Daniel Brown",
                "phone": "+888777666",
                "email": "daniel.brown@example.com",
            },
            "image": "https://images.prop24.com/kg3s7f5airvmltt4k7edfchahy/Crop237x198",
        },
        {
            "title": "Diani Beach Retreat",
            "type": "For Rent",
            "price": "Ksh 28,000/month",
            "bedrooms": 2,
            "bathrooms": 1,
            "location": "Diani",
            "city": "Mombasa",
            "propertyFeatures": ["Beachfront Living", "Garden", "Security"],
            "squareFootage": 1200,
            "contactInformation": {
                "name": "Ava Brown",
                "phone": "+555666777",
                "email": "ava.brown@example.com",
            },
            "image": "https://images.prop24.com/sdbobo5qnvtvfvxre4k7z5k47m/Crop237x198",
        },
        {
            "title": "Cityscape Apartment",
            "type": "For Rent",
            "price": "Ksh 20,000/month",
            "bedrooms": 1,
            "bathrooms": 1,
            "location": "Kahawa",
            "city": "Nairobi",
            "propertyFeatures": ["Urban Living", "Modern Finishes", "Security"],
            "squareFootage": 800,
            "contactInformation": {
                "name": "Lucas Wilson",
                "phone": "+111222333",
                "email": "lucas.wilson@example.com",
            },
            "image": "https://images.prop24.com/jkycczarbrygqfg6wx3wgsce7i/Crop237x198",
        },
        {
            "title": "Mombasa Paradise",
            "type": "For Rent",
            "price": "Ksh 38,000/month",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Nyalani",
            "city": "Mombasa",
            "propertyFeatures": ["Coastal Living", "Balcony", "Security"],
            "squareFootage": 1500,
            "contactInformation": {
                "name": "Olivia White",
                "phone": "+999888777",
                "email": "olivia.white@example.com",
            },
            "image": "https://images.prop24.com/sey3yv7wvsab4lx5mnpl3lqiya/Crop237x198",
        },
        {
            "title": "Nairobi Heights",
            "type": "For Rent",
            "price": "Ksh 25,000/month",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Roysambu",
            "city": "Nairobi",
            "propertyFeatures": ["Panoramic Views", "Balcony", "Swimming Pool"],
            "squareFootage": 1300,
            "contactInformation": {
                "name": "Emma Wilson",
                "phone": "+111222333",
                "email": "emma.wilson@example.com",
            },
            "image": "https://images.prop24.com/uahuyxpi7plmal7yjya3v7pw5y/Crop237x198",
        },
        {
            "title": "Beachside Condo",
            "type": "For Rent",
            "price": "Ksh 30,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Mtwapa",
            "city": "Mombasa",
            "propertyFeatures": ["Seaside Living", "Modern Design", "Security"],
            "squareFootage": 1800,
            "contactInformation": {
                "name": "Daniel White",
                "phone": "+888777666",
                "email": "daniel.white@example.com",
            },
            "image": "https://images.prop24.com/notevjgefd3qii3kobo4jufavm/Crop237x198",
        },
        {
            "title": "Kisumu Oasis",
            "type": "For Rent",
            "price": "Ksh 32,000/month",
            "bedrooms": 2,
            "bathrooms": 2,
            "location": "Kisumu",
            "city": "Kisumu",
            "propertyFeatures": ["Lake Views", "Modern Finishes", "Security"],
            "squareFootage": 1400,
            "contactInformation": {
                "name": "Sophia Brown",
                "phone": "+333444555",
                "email": "sophia.brown@example.com",
            },
            "image": "https://images.prop24.com/sey3yv7wvsab4lx5mnpl3lqiya/Crop237x198",
        },
        {
            "title": "Sunset Villa",
            "type": "For Rent",
            "price": "Ksh 28,000/month",
            "bedrooms": 3,
            "bathrooms": 2,
            "location": "Kizingo",
            "city": "Mombasa",
            "propertyFeatures": ["Evening Views", "Garden", "Security"],
            "squareFootage": 1600,
            "contactInformation": {
                "name": "Sophie White",
                "phone": "+555666777",
                "email": "sophie.white@example.com",
            },
            "image": "https://images.prop24.com/ckmwgegvhg2jgxc6mmylyqztyi/Crop237x198",
        },
        {
            "title": "Urban Living Studio",
            "type": "For Rent",
            "price": "Ksh 15,000/month",
            "bedrooms": 1,
            "bathrooms": 1,
            "location": "Kariobangi",
            "city": "Nairobi",
            "propertyFeatures": ["City Lifestyle", "Modern Design", "Security"],
            "squareFootage": 700,
            "contactInformation": {
                "name": "Oliver White",
                "phone": "+999888777",
                "email": "oliver.white@example.com",
            },
            "image": "https://images.prop24.com/6wrg4etmqmmg4qgwdxsad7wj5y/Crop237x198",
        },
    ],
    "reviews": [],
}

with app.app_context():
    Property.query.delete()
    ContactInformation.query.delete()
    Review.query.delete()

    for listing in data["listings"]:
        # Check if the contact already exists
        contact = ContactInformation.query.filter_by(
            name=listing["contactInformation"]["name"],
            phone=listing["contactInformation"]["phone"],
            email=listing["contactInformation"]["email"],
        ).first()

        if not contact:
            contact = ContactInformation(
                name=listing["contactInformation"]["name"],
                phone=listing["contactInformation"]["phone"],
                email=listing["contactInformation"]["email"],
            )
            db.session.add(contact)
            db.session.commit()

        # Create the property entry
        property_entry = Property(
            title=listing["title"],
            type=listing["type"],
            price=listing["price"],
            bedrooms=listing["bedrooms"],
            bathrooms=listing["bathrooms"],
            location=listing["location"],
            city=listing["city"],
            square_footage=listing["squareFootage"],
            image=listing["image"],
            contact_id=contact.id,
            property_features=listing["propertyFeatures"],
        )

        db.session.add(property_entry)

    # Handle reviews if they exist in your JSON data
    for review in data["reviews"]:
        review_entry = Review(house_id=review["house_id"], review=review["review"])
        db.session.add(review_entry)

    # Commit all changes to the database
    db.session.commit()

print("Database seeded successfully!")
